
[workspace]
resolver = "3"
members = [
  "compiler/dragonfly-ast",
  "compiler/dragonfly-span",
  "compiler/dragonfly-lexer",
]

[workspace.package]
edition = "2024"
repository = "https://github.com/nearest-river/dragonfly.git"
authors = ["Nate River"]

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
thiserror = "2.0.17"
unescape = "0.1.0"
half = "2.7.1"
f128 = "0.2.9"
unicode-ident = "1.0.24"
unicode-properties = { version = "0.1.4", features = ["emoji"] }
lexical = { version = "7.0.5", features = ["f128", "compact", "f16", "floats", "format", "integers", "lint", "parse", "power-of-two", "radix"] }
lexical-core = { version = "1.0.6", features = ["f128", "compact", "f16", "floats", "format", "integers", "lint", "parse", "power-of-two", "radix"] }
lexical-util = { version = "1.0.7", features = ["f128", "compact", "f16", "float16", "parse-floats", "parse-integers", "power-of-two", "radix", "write-floats", "write-integers", "format", "lint"] }
unicode-id-start = "1.4.0"




