[package]
name = "dragonfly-ast"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
dragonfly-span = { path = "../dragonfly-span/" }
dragonfly-lexer = { path = "../dragonfly-lexer/" }
dragonfly-index = { path = "../dragonfly-index/" }
dragonfly-stable-hash = { path = "../dragonfly-stable-hash/" }



