[package]
name = "dragonfly-lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
dragonfly-span = { path = "../dragonfly-span" }
workspace.thiserror = true
workspace.unescape = true
workspace.half = true
workspace.f128 = true
workspace.unicode-ident = true
workspace.unicode-properties = true
workspace.lexical = true
workspace.lexical-core = true
workspace.lexical-util = true
workspace.unicode-id-start = true




