[package]
name = "dragonfly-lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
dragonfly-span = { path = "../dragonfly-span" }
thiserror.workspace = true
unescape.workspace = true
half.workspace = true
f128.workspace = true
unicode-ident.workspace = true
unicode-properties.workspace = true
lexical.workspace = true
lexical-core.workspace = true
lexical-util.workspace = true
unicode-id-start.workspace = true




