[package]
name = "dragonfly-span"
version = "0.1.0"
edition = "2024"

[dependencies]
dragonfly_data_structures = { path = "../dragonfly_data_structures/" }
dragonfly-arena = { path = "../dragonfly-arena/" }
dragonfly-stable-hash = { path = "../dragonfly-stable-hash/" }
dragonfly-index = { path = "../dragonfly-index/" }
itoa.workspace = true

